name: branch2

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: rome-pulumi-runner-label-1
    
    steps:
      - name: Print current working directory
        run: pwd

      - name: Test
        run: |          
            echo "GCP_PROJECT...${{ vars.GCP_PROJECT }}"         
            echo "GCP_ZONE...${{ vars.GCP_ZONE }}"  
