name: Destroy

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  pulumi-destroy:
    name: pulumi-destroy
    runs-on: pulumi-rome-runner-label-1
    environment: dev

    env:
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      GCP_ZONE: ${{ vars.GCP_ZONE }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}

    steps:
      - name: Set Google Cloud credentials
        run: |
          echo "$GCP_CREDENTIALS" > /home/itadmin/sa/service-account-key.json    

      - name: Test
        run: |          
            echo "GCP_PROJECT...$GCP_PROJECT"         
            echo "GCP_ZONE...$GCP_ZONE" 
            echo "PULUMI_ACCESS_TOKEN......$PULUMI_ACCESS_TOKEN"
            echo "GCP_CREDENTIALS......$GCP_CREDENTIALS"
            echo "GCP_SERVICE_ACCOUNT...$GCP_SERVICE_ACCOUNT" 

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd
        
      - name: Check Pulumi version
        run: pulumi version

      - name: Check gcloud version
        run: gcloud --version       

      - name: Check if stack exists
        id: check_stack
        run: pulumi stack select sbsr-ghc-pulumi-org/sample-pulumi-project/dev-1 || echo "STACK_DOES_EXIST"

      # Uncomment the following step if needed
      # - name: Print stack existence check result        
      #   run: |
      #     echo "Stack existence check result: ${{ steps.check_stack.outputs.check_stack }}"

      - name: Destroy Infra        
        uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: sbsr-ghc-pulumi-org/sample-pulumi-project/dev-1