name: branch

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: rome-pulumi-runner-label-1
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create the resources
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: sample-pulumi-project-dev          
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}