name: Preview

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: pulumi-rome-runner-label-1
    environment: dev

    env:
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      GCP_ZONE: ${{ vars.GCP_ZONE }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}

    steps:
      - name: Set Google Cloud credentials
        run: |
          echo "$GCP_CREDENTIALS" > /home/itadmin/sa/service-account-key.json    

      - name: Test
        run: |          
            echo "GCP_PROJECT...$GCP_PROJECT"         
            echo "GCP_ZONE...$GCP_ZONE" 
            echo "PULUMI_ACCESS_TOKEN......$PULUMI_ACCESS_TOKEN"
            echo "GCP_CREDENTIALS......$GCP_CREDENTIALS"
            echo "GCP_SERVICE_ACCOUNT...$GCP_SERVICE_ACCOUNT" 

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd
        
      - name: Check Pulumi version
        run: pulumi version

      - name: Check gcloud version
        run: gcloud --version       

      - name: Check if stack exists
        id: check_stack
        run: |
           pulumi stack ls | grep -q "sbsr-ghc-pulumi-org/dev-1" && echo "STACK_DOES_EXIST" || echo "STACK_DOES_NOT_EXIST"
      
      - name: Print stack existence check result        
        run: |
           echo "Stack existence check result: ${{ steps.check_stack.outputs.stdout }}"
      

      # - name: Initialize Pulumi stack if it doesn't exist        
      #   run: pulumi stack init sbsr-ghc-pulumi-org/sample-pulumi-project/dev-1 


      # Uncomment the following steps as needed
      # - name: Create pulumi configuration
      #   run: | 
      #      pulumi config set gcp:project $GCP_PROJECT 
      #      pulumi config set gcp:zone $GCP_ZONE
      #      pulumi config set gcp:credentials /home/itadmin/sa/service-account-key.json          
      #      gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=/home/itadmin/sa/service-account-key.json

      # - name: Create GKE resources
      #   uses: pulumi/actions@v3
      #   with:
      #     command: up
      #     stack-name: sbsr-ghc-pulumi-org/sample-pulumi-project/dev-1
